"""removed isdeleted

Revision ID: 8a10c1858e50
Revises: 07b5c5241d75
Create Date: 2026-08-20 07:59:57.746838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a10c1858e50'
down_revision: Union[str, Sequence[str], None] = '07b5c5241d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isDeleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isDeleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
